name: Test VM Host

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check VM Host
        run: |
          if [ -z "${{ secrets.VM_HOST }}" ]; then
            echo "VM_HOST IS EMPTY"
            exit 1
          else
            echo "VM_HOST IS AVAILABLE"
          fi
